# Generated by Django 3.1.2 on 2020-10-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitit',
            name='trans_date',
            field=models.DateTimeField(),
        ),
    ]
