# Generated by Django 3.1.2 on 2020-10-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20201005_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_trans', models.CharField(max_length=200)),
                ('value_trans', models.FloatField()),
                ('trans_date', models.DateTimeField()),
            ],
        ),
    ]
