# Generated by Django 3.1.2 on 2020-10-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_creditit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=200)),
                ('total_cash', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='creditit',
            name='author_trans',
        ),
        migrations.RemoveField(
            model_name='debitit',
            name='author_trans',
        ),
    ]
