# Generated by Django 3.1.2 on 2020-10-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20201005_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditIt',
        ),
        migrations.DeleteModel(
            name='DebitIt',
        ),
    ]
