# Generated by Django 3.1.2 on 2020-10-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20201005_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
