# Generated by Django 3.1.2 on 2020-10-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_auto_20201005_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='total_credit',
            field=models.FloatField(default='1000.00'),
        ),
    ]
