# Generated by Django 3.1.2 on 2020-10-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_conta_total_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.IntegerField()),
                ('cash_trans', models.FloatField()),
            ],
        ),
    ]
