# Generated by Django 3.1.2 on 2020-10-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_debitit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitit',
            name='receiver',
        ),
    ]
