# Generated by Django 3.1.2 on 2020-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_remove_debitit_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitit',
            name='author_trans',
            field=models.IntegerField(default=0),
        ),
    ]
