# Generated by Django 3.1.2 on 2020-10-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_debitit_author_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitit',
            name='author_receiver',
            field=models.IntegerField(default=0),
        ),
    ]
