# Generated by Django 3.1.2 on 2020-10-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_debitit_author_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitit',
            old_name='author_receiver',
            new_name='trans_receiver',
        ),
    ]
