# Generated by Django 3.1.2 on 2020-10-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_auto_20201006_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_cred', models.IntegerField(default=0)),
                ('cred_receiver', models.IntegerField(default=0)),
                ('cash_trans', models.FloatField()),
            ],
        ),
    ]
