# Generated by Django 3.1.2 on 2020-10-06 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_creditit'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='creditit',
            name='credited_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='debitit',
            name='debited_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
