# Generated by Django 3.1.2 on 2020-10-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20201006_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='creditit',
            name='credited_date',
        ),
        migrations.RemoveField(
            model_name='debitit',
            name='debited_date',
        ),
    ]
